### ISSUE TITLE
查理 · 芒格

### ISSUE THREAD

**Issue by sisisimao** [sisisimao/cards#26]
兜转了两年，似乎又回到起点。

**Comment by sisisimao** [comment]
比如说，查理思考问题总是从逆向开始。如果要明白人生如何得到幸福，查理首先是研究人生如何才能变得痛苦；要研究企业如何做强做大，查理首先研究企业是如何衰败的；大部分人更关心如何在股市投资上成功，查理最关心的是为什么在股市投资上大部分人都失败了。他的这种思考方法来源于下面这句农夫谚语中所蕴含的哲理：我只想知道将来我会死在什么地方，这样我就不去那儿了。

查理在他漫长的一生中，持续不断地研究收集关于各种各样的人物、各行各业的企业以及政府管治、学术研究等各领域中的人类失败之著名案例，并把那些失败的原因排列成正确决策的检查清单，使他在人生、事业的决策上几乎从不犯重大错误。这点对巴菲特及伯克希尔五十年业绩的重要性是再强调也不为过的。

_来源：《穷查理宝典》中文版序_

**Comment by sisisimao** [comment]
你必须知道重要学科的重要理论，并经常使用它们——要全部都用上，而不是只用几种。大多数人都只养成一个学科——比如说经济学——的思维模型，试图用一种方法来解决所有问题。你知道谚语是怎么说的：“在手里拿着铁锤的人看来，世界就像一颗钉子。”这是一种处理问题的笨方法。

**Comment by sisisimao** [comment]
许多年轻的生意人都问我们这个问题。这是一个聪明的问题：你看见某个有钱的老头，然后问他：“我要怎样才能变得像你一样呢？

”每天起床的时候，争取变得比你从前更聪明一点。认真地、出色地完成你的任务。慢慢地，你会有所进步，但这种进步不一定很快。但你这样能够为快速进步打好基础……每天慢慢向前挪一点。到最后——如果你足够长寿的话——大多数人得到了他们应得的东西。

**Comment by sisisimao** [comment]
我本人是个传记书迷。我觉得你要是想让人们认识有用的伟大概念，最好是将这些概念和提出它们的伟人的生活和个性联系起来。我想你要是能够和亚当·斯密交朋友，那你的经济学肯定可以学得更好。和“已逝的伟人”交朋友，这听起来很好玩，但如果你确实在生活中与已逝的伟人成为朋友，那么我认为你会过上更好的生活，得到更好的教育。这种方法比简单地给出一些基本概念好得多。

**Comment by caifreecom** [comment]
测试添加。2017016.
